version: "3.9"
services:
  mariadb:
    build:
      context: ./mariaDB
      network: hunts
    restart: always
    container_name: mariadb
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: ffxiv2
      MYSQL_USER: hunts
      MYSQL_PASSWORD: 
    networks: 
      - hunts

  ffxivhunts:
    build:
      context: ./ffxivhunts
      network: hunts
    container_name: hunts
    ports: 
      - 80:80
    environment: 
      DB_CONNECTION: mariadb
      DB_USER: hunts
      DB_PASS: 
      DB_SCHEMA: ffxiv2
    networks: 
      - hunts
    links: 
      - mariadb
    depends_on: 
      - mariadb

networks: 
  hunts:
    external: true